### ISSUE TITLE
Swap from google analytics to an open-source alternative

### ISSUE THREAD

**Issue by L1lith** [bestofjs/bestofjs#105]
I was browsing the site and noticed that it loaded a script from google-analytics.com. Perhaps using an open-source and/or self-hosted solution would be better than google analytics from a privacy perspective. I haven't tried implementing anything like this myself, but perhaps [Matomo](https://matomo.org/) might be a good solution? This isn't a giant issue but I've been trying to reduce how much I expose myself and my users to companies that like to mine and sell data.

**Comment by michaelrambeau** [comment]
Hello @L1lith 
Thank you for the idea.
I totally agree with you, actually I searched recently for some alternatives but I couldn't find anything that was free.

The current number of monthly Page Views is around 90,000 according to Google Analytics but I guess the real numbers are bigger since developers often use solutions to avoid being tracked.

So I'm going to investigate seriously about this issue and try to implement something.
Just in case, have you any feedback about https://www.cloudflare.com/analytics/ ?

**Comment by L1lith** [comment]
@michaelrambeau Here's one [blog](https://www.ctrl.blog/entry/review-cloudflare-analytics.html) I found detailing the merit of Cloudflare analytics. It appears to be overall a good option, though it might be worth looking into the cookie issue talked about inside the article. 

Overall finding quality free services is a difficult thing. Free software is fairly abundant but it all requires a back-end to host it (which isn't free). I think for now Cloudflare would be the best choice.

**Comment by michaelrambeau** [comment]
Thank you @L1lith  for the feedback, Cloudflare seems simplest solution to integrate as it's just a snippet and no setup is required, so I'm going to try it ASAP.

We have a tag "analytics" in _Best of JS_ actuallly: https://bestofjs.org/projects?tags=analytics

What do you think of the solution Ackee? https://docs.ackee.electerious.com/

I like the fact it runs on Node.js and on MongoDB (the stack I'm familiar with), it could be installed easily on Vercel, it seems.

**Comment by michaelrambeau** [comment]
## Before saying goodbye

Before removing GoogleAnalytics, for the records, here is a screenshot about the number of monthly Page Views since the creation of the project.
There was a peak of 166k PageViews in June 2019.
The number is steadily decreasing since that: 94k in April 2021.

![image](https://user-images.githubusercontent.com/5546996/119984279-2e09f380-bffc-11eb-94b1-bb081a98ea70.png)

[Analytics All Web Site Data Overview 20151201-20210527.pdf](https://github.com/bestofjs/bestofjs-webui/files/6560844/Analytics.All.Web.Site.Data.Overview.20151201-20210527.pdf)

**Comment by michaelrambeau** [comment]
## Trying Cloudflare analytics

I added the snippet to enable Cloudflare Analytics yesterday.
24 hours later, the following numbers are displayed:

- 1.64 visits
- 2.51 k Page views (that would mean 75k a month but it's better to wait for a full week before making any interpolation)

![image](https://user-images.githubusercontent.com/5546996/120069585-9a025f80-c0c1-11eb-84bf-e26a60d03e0a.png)

**Comment by michaelrambeau** [comment]
Among other changes released on 2021-05-31 #103 GoogleAnalytics tracking code has been removed.

**Comment by L1lith** [comment]
@michaelrambeau Nice work! If you ever feel like going with a self-hosted solution, I think that this section [here](https://github.com/electerious/Ackee/blob/master/docs/FAQ.md#how-does-ackee-compare-to-matomo-piwik) describes the differences between it and Matomo (Matomo looks like a paid service but I'm pretty sure it's fully free and open source for you to host yourself, the provided hosting is optional) well, and they are the only 2 major projects I've come across online. To summarize Ackee is more lightweight and & Matomo is closer in functionality to Google Analytics, but it also is more CPU intensive.

**Comment by michaelrambeau** [comment]
Thank you @L1lith , to me the lighter, the better, I only need an overview if the number of page views, this is why _Ackee_ sounds interesting.

A paid option (that is also an open-source project you can host) that I find very good and that was recommended to me: https://plausible.io/

I have just opened an "Open Collective" account because someone asked me, maybe I should set a "goal" asking people to sponsor the feature https://opencollective.com/bestofjs what do you think?

**Comment by L1lith** [comment]
@michaelrambeau Yeah I was reading over plausible, it seems like a good options too. I also like the idea of an accepting donations for the project. Perhaps this would be a good moment to reflect on the long-term goals of the project. Perhaps we could look at ways to reach out to the broader development community and get the project seen by more people (I know here meetup coding groups allow people to talk about their projects, or you could try to find ways through social media and content creators). I think if we could increase traffic then more people might be willing to contribute to the project financially or other with pull requests, etc. 

Open Collective seems like a good resource for receiving payments, and I think it can work for the project

**Comment by michaelrambeau** [comment]
Thank you for the comments @L1lith .

I've just published the first news on Open Collective: https://opencollective.com/bestofjs/updates/june-2021-news

Also, for the records, I'm including a screenshot of the analytics from Cloudflare after one full week (23.6k Page views)

![image](https://user-images.githubusercontent.com/5546996/120917420-2cba8400-c6ea-11eb-8484-a40a0f68981a.png)

**Comment by HenrikFricke** [comment]
For our websites, we also switched from Google Analytics to Plausible. 

We are super happy with the simplicity of the service, especially the dashboard is so clean and gives us all the basic metrics we care about. I also like, that you can set the dashboards to public and easily share them (e.g. have a link in the footer of the website). 

Though, for your traffic, the hosted version might be a bit expensive.

**Comment by michaelrambeau** [comment]
Thank you @HenrikFricke for the comments.

So you too, you recommend Plausible. I'd like to have a public dashboard like you do on https://yetanother.blog/ (the "stats" link at the bottom) 

Here are the latest numbers from Cloudflare: more than 100 k PageViews the last month:

![image](https://user-images.githubusercontent.com/5546996/124522570-b450fb00-de2e-11eb-8f63-25e6863738ab.png)

The [pricing page](https://plausible.io/#pricing) of Plausible says:

- Monthly pageviews 100k => $12 / mo
- Monthly pageviews 200k => $20 / mo

So I guess the cost would $20 by month. Maybe we could ask to sponsor the project by providing analytics if we mention them with something like "Analytics provided by Plausible".

**Comment by michaelrambeau** [comment]
Closing the issue as we use CloudFlare analytics in production and we are going to release a brand new version of the app, built with Next.js.

With the new "server-centric" approach, we don't need to track users on the client-side, it seems Vercel provides a solution that I have to check: https://vercel.com/docs/concepts/analytics/quickstart

Anyway any suggestion is welcome as all I need is an idea of the traffic and the pages that have traction, and that I'd like to make public as I have nothing to hide.
