### ISSUE TITLE
Make the website operate without JavaScript

### ISSUE THREAD

**Issue by L1lith** [bestofjs/bestofjs#114]
This would be a nifty feature for people with JS disabled in their browser

**Comment by michaelrambeau** [comment]
Thank you for the suggestion @L1lith 
I think having SSG provided by Next.js (like mentioned in the roadmap #109 ) could at least make the top page visible for people who don't have JavaScript enabled?

Having the full features available without JavaScript may be very challenging as lot of things happen in the browser currently (search and filter features) but I agree that it would be great to make the site available without JavaScript (and it would be a bit ironic for a site called _Best of JS!_).

**Comment by L1lith** [comment]
[We could consider Astro's SSR mode, though Vite might already do that I'm not sure](https://docs.astro.build/en/guides/server-side-rendering/)

**Comment by michaelrambeau** [comment]
Closing the issue as the beta version https://beta.bestofjs.org/ can work without JavaScript!

Well most of the features, except the search feature (Cmd+K to open search popup) that works on the client-side.

it would be cool to make this search feature available even without JavaScript but making the search input field editable and go to the search URL when submitting (without Ajax), because we already have search URLs! (E.g. https://beta.bestofjs.org/projects?query=sindre)

I can't wait for your contribution to make it happen 😄
