### ISSUE TITLE
Implement a Content Security Policy

### ISSUE THREAD

**Issue by L1lith** [bestofjs/bestofjs#121]
You can read more [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), but basically an effective Content Security Policy is an easy way to increase the security of any webpage. If you cannot change the HTTP headers you can set it via a meta tag in the <head>

**Comment by michaelrambeau** [comment]
Thank you for the suggestion @L1lith 

Just in case, you don't want to make a PR so that I can see it would work, taking into account all the external HTTP requests we do:

- initial JSON data from  `bestofjs-static-api.vercel.app` domain
- JSON data and HTML content from serverless functions running on `bestofjs-serverless.now.sh` domain
- GitHub avatars
- CloudFlare analytics
- ... ?

Not to mention that when I'm developing the JSON data come from other domains that the ones I mention (localhost something)...

I'm working on a new architecture (using Next.js) so the situation may change soon (there should be less external requests if serverless functions are from the same Next.js application).

**Comment by michaelrambeau** [comment]
Closing the issue as the Next.js version is now in beta, but feel free to suggest or implement any change :)
