### ISSUE TITLE
Use Klass instead of CVA

### ISSUE THREAD

**Issue by flamrdevs** [bestofjs/bestofjs#248]
Use [klass](https://github.com/flamrdevs/klass) instead of cva for class variant utility.

See [benchmark](https://github.com/flamrdevs/klass-benchmark).

Klass also has more features such as `groups` and `slots` that can be used on compound components pattern like DropdownMenu.

**Comment by michaelrambeau** [comment]
Thank you @flamrdevs for the PR and for that library!

To provide more context, could you provide a short overview of the benefits of using `Klass` instead of the current approach (besides the performance improvement)?

It's your project so it may be obvious for you 😄 

Not related to the "issue": Did you know we have a `className` tag in _Best of JS_, maybe we could Klass here?

**Comment by michaelrambeau** [comment]
Something I find very interesting: `reklass` allows the creation of layout components you can style by using props, I'm a big fan of ChakraUI `Box` component (and its friends `<Flex>`, `<Stack>`...), I find the code far much readable than using long classNames.

```jsx
<Box m={{ base: "1", md: "2" }} p="2">
  <Box as="section">
    <Button color="primary" block>
      Primary Block Button
    </Button>
  </Box>
</Box>
```

So I think we could improve the codebase by introducing `Klass` and `Reklass` 👍

**Comment by flamrdevs** [comment]
😄😄😄
The purpose still same, to construct className, but `Klass` has more features, also built-in integration for popular framework.

**Comment by flamrdevs** [comment]
`reklass` was created to handle responsive variants, but requires some additional configuration, such as setting up a safelist in the tailwind configuration.
