### ISSUE TITLE
Inconsistent Icons

### ISSUE THREAD

**Issue by flamrdevs** [bestofjs/bestofjs#259]
1. The `bestofjs-nextjs` app has multiple icons library, `react-icons`, `@heroicons/react`, `lucide-icons`. Then based on this [PR](https://github.com/bestofjs/bestofjs/pull/224), why only some of them are transformed into svg sprites. why not all icons?.

2. Is it possible to use just one of them (`react-icons`/`@heroicons/react`/`lucide-icons`)? I suggest `lucide-icons`.

So here, I emphasize using SVG sprites for all icons.

The benefits are not only for production, but also for development(install,dev,build):
- reduce installed packages, install faster
- dev mode faster
- build mode faster
- (production) render faster and smaller bundle size

**Comment by michaelrambeau** [comment]
Thank you @flamrdevs for your interest about the project!

I will do more cleanup related to icons.

I think SVG sprites are great for icons that appear in multiple places (several times in the same page or shared by different pages).

However if there is one single page that uses one one single icon, it does not really provide any benefit, because the `sprite.svg` file is loaded by all pages of the app, so we could bloat the sprite file with icons that are not necessary. For _Best of JS_, it's not really a problem as we don't have a huge variety of pages and icons.

`bestofjs-webui` still needs to be shipped because we miss the feature to let authenticated users bookmark projects.

For more context, when we released the Next.js app, a user complained about the missing feature: https://github.com/bestofjs/bestofjs/issues/176#issuecomment-1705795983

This is the reason I made the previous SPA available at `classic.bestofjs.org`.

I will try to add the missing feature.

An overview of the tasks I'd like to work on: https://github.com/orgs/bestofjs/projects/1
